name: Test

on:
  push:
    tags-ignore:
    - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: {go-version: '^1.18'}
    - run: go mod download
    - run: go build ./...
    - run: go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45.2
